image: ubuntu:rolling

gcf-build:
  script:
  - apt-get update
  - apt-get install -y wamerican wdutch wfrench wngerman witalian wspanish
  - bash generate-wordlist.sh > wordlist.json
  artifacts:
    paths:
    - index.js
    - package.json
    - wordlist.json